name: main

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/rust@v1
    - uses: wtnb75/actions/cargotest@v1
      with:
        html-output-dir: coverage
    - name: cargo doc
      run: |
        cargo doc --no-deps
        mv target/doc docs
        crate=$(cargo metadata --no-deps --format-version=1 \
          | jq -r '.packages[0].targets[] | select(.kind[0]=="lib") | .name')
        echo "<!DOCTYPE html><meta http-equiv=\"refresh\" content=\"0; url=${crate}/index.html\">" \
          > docs/index.html
      shell: bash
    - uses: wtnb75/actions/merge-pages@v1
      with:
        dirs: "docs coverage"
    - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

  deploy:
    needs: build
    if: github.ref_name == 'master'
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: deploy pages
      id: deployment
      uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
